sonar.qualitygate.wait=true
sonar.projectKey=lhassan-oubihi-eng_lafarge-truck-traffic
sonar.organization=lhassan-oubihi-eng
sonar.python.version=3.12
sonar.sources=app
sonar.tests=app/tests
sonar.exclusions=app/tests/**
sonar.terraform.provider.aws.version=5.0
sonar.coverage.exclusions=**/*.tf,terraform/**/*.tf,**/Dockerfile,**/tests/**
sonar.python.coverage.reportPaths=coverage.xml
